apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: istio-system
spec:
  type: ExternalName
  externalName: tempo.monitoring.svc.cluster.local
  ports:
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
