# Synthetic Monitoring - Blackbox Exporter + Probes
# HTTP/HTTPS endpoint monitoring for GitHub Gists API

apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: monitoring
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200]
          method: GET
          follow_redirects: true
          fail_if_ssl: false
          fail_if_not_ssl: false
          tls_config:
            insecure_skip_verify: true
      
      http_post_2xx:
        prober: http
        timeout: 5s
        http:
          method: POST
          valid_status_codes: [200, 201]
          tls_config:
            insecure_skip_verify: true
      
      http_json:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          valid_status_codes: [200]
          method: GET
          headers:
            Accept: application/json
          fail_if_body_not_matches_regexp:
            - '"status":\s*"healthy"'
          tls_config:
            insecure_skip_verify: true
      
      tcp_connect:
        prober: tcp
        timeout: 5s
      
      icmp:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: ip4

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9115"
    spec:
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:v0.24.0
        ports:
        - containerPort: 9115
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox_exporter
        args:
        - --config.file=/etc/blackbox_exporter/blackbox.yml
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config
        configMap:
          name: blackbox-exporter-config

---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app: blackbox-exporter
spec:
  selector:
    app: blackbox-exporter
  ports:
  - port: 9115
    targetPort: 9115
    name: http

---
# Prometheus ServiceMonitor for Blackbox
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  endpoints:
  - port: http
    interval: 30s
    path: /metrics

---
# Synthetic Monitoring Probes
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: gists-api-health
  namespace: monitoring
  labels:
    release: monitoring
spec:
  interval: 30s
  module: http_json
  prober:
    url: blackbox-exporter:9115
  targets:
    staticConfig:
      static:
      - https://gists.kishore.local/health
      - https://gists.local/health
      labels:
        service: github-gists-api
        probe_type: health

---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: gists-api-endpoints
  namespace: monitoring
  labels:
    release: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter:9115
  targets:
    staticConfig:
      static:
      - https://gists.kishore.local/metrics
      - https://gists.kishore.local/octocat
      - https://gists.kishore.local/cache/stats
      labels:
        service: github-gists-api
        probe_type: endpoint

---
# PrometheusRule for Synthetic Monitoring Alerts
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: synthetic-monitoring-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: synthetic-monitoring
    rules:
    - alert: EndpointDown
      expr: probe_success == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Endpoint {{ $labels.instance }} is down"
        description: "{{ $labels.instance }} has been unreachable for more than 2 minutes."
    
    - alert: SlowEndpoint
      expr: probe_duration_seconds > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Endpoint {{ $labels.instance }} is slow"
        description: "{{ $labels.instance }} response time is above 2 seconds."
    
    - alert: SSLCertExpiringSoon
      expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: "SSL certificate expiring soon"
        description: "SSL certificate for {{ $labels.instance }} expires in less than 30 days."
